#cloud-config
users:
  - name: ubuntu
    ssh-authorized-keys:
      - ${ssh_keys}
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    shell: /bin/bash

packages:
  - nginx

runcmd:
  - systemctl start nginx
  - systemctl enable nginx
