#cloud-config
users:
  - name: ubuntu
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILaSmBdeVgjoxZxoR6EomPvkzN/a2MFz+P23PVCX6DIf root@killakazzak.fvds.ru
package_update: true
package_upgrade: false
packages:
  - vim
